blog/urls.py
from django.urls import path, re_path

# import blog.views as nikai
from . import views
from .api.myapi import SwaggerSchemaView

# 此处的app_name要和myblog种urls中的namespace保持一致
app_name = "blog"

urlpatterns = [
    path('myindex/', views.index),
    path('index/', views.index2),
    path('article/', views.getuser),
    path('articles/', views.getAll),
    path('article/<int:article_id>/', views.getPage, name='article_page'),
    path('update/<int:article_id>', views.edit_page, name='edit_page'),
    path('edit/action', views.edit_action, name='edit_action'),
    path('api/swagger', SwaggerSchemaView.get, name='get_json'),
    path('task/', views.do, name='do')
]

blog2/urls.py
from django.urls import path

# import blog.views as nikai
from . import views

urlpatterns = [
    path('index/', views.index),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.api.myapi import SwaggerSchemaView
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from rest_framework.permissions import AllowAny

# import blog.views as nikai
from blog import views as nikai


schema_view = get_schema_view(title='my API', renderer_classes=[OpenAPIRenderer, SwaggerUIRenderer]
                              , permission_classes=())

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('docs/', SwaggerSchemaView.as_view(), name='apiDocs'),
    path('docs/', schema_view, name='apiDocs'),
    path('index/', nikai.index),
    path('blog/', include('blog.urls', namespace='blog')),
    path('blog2/', include('blog2.urls')),

]

blog/models.py
from django.db import models


# Create your models here.
# 类似java的DTO

class Article(models.Model):
    title = models.CharField(max_length=32, default='title')
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

blog2/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

from . import models
from .tasks import *
from django.http import JsonResponse

# Create your views here.
# 类似java的controller

HTTP_HOST = 'HTTP_HOST'


def index(request):
    print(request.path)

    meta_ = request.META
    if meta_ is not None:
        if HTTP_HOST in meta_:
            host_ = meta_[HTTP_HOST]
            print(host_)
        # for key in meta_:
        #     print(key + "=" + meta_[key])

    return HttpResponse(host_)


def getuser(request):
    article = models.Article.objects.get(pk=1)
    return render(request, 'blog/index2.html', {'article': article})


def index2(request):
    return render(request, 'blog/index.html', {'xixi': 'This is first page'})


def getAll(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/home.html', {'articles': articles})


def getPage(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/home_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/update.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/update.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id')
    if str(article_id) == '0':
        models.Article.objects.create(title=title, content=content)
        return render(request, 'blog/home.html', {'articles': models.Article.objects.all()})
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/home.html', {'articles': models.Article.objects.all()})


def do(request):
    """
    任务
    :param request:
    :return:
    """
    print("start do task")
    BlogTask.delay()
    print("end do task")
    return JsonResponse({"result": "success"})

blog2/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(requset):
    return render(requset,'blog2/index.html')

blog/templates/blog/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>articles</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
</h1>
{% for article in articles %}

    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br>

{% endfor %}

</body>
</html>

blog/templates/blog/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<h2>{{ article.content }}</h2>
<br>
<a href="{% url 'blog:edit_page' article.id %}">修改</a>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My blog</title>
</head>
<body>
<h1>

    {{ xixi }}
</h1>
</body>
</html>

blog/templates/blog/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Model test</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<h2>{{ article.content }}</h2>
</body>
</html>

blog/templates/blog/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}

    {% comment %}    {% if  article %}
        <input type="hidden" name="article_id" value="{{ article.id }}">
        <label>Title
            <input type="text" name="title" value="{{ article.title }}">
        </label><br>
        <label>content
            <input type="text" name="content" value="{{ article.content }}">
        </label><br>
    {% else %}
        <label>Title
            <input type="text" name="title">
        </label><br>
        <label>content
            <input type="text" name="content">
        </label><br>
    {% endif %}{% endcomment %}

    <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
    <label>Title
        <input type="text" name="title" value="{{ article.title }}">
    </label><br>
    <label>content
        <input type="text" name="content" value="{{ article.content }}">
    </label><br>
    <input type="submit" value="submit">
</form>
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog2</title>
</head>
<body>
<h1>
    nikai
</h1>
</body>
</html>